import Head from 'next/head'
import Coluna1 from './colunas/coluna1'
import Coluna2 from './colunas/coluna2'
import Coluna3 from './colunas/coluna3'
import Coluna4 from './colunas/coluna4'
import Coluna5 from './colunas/coluna5'
import colunas from '../../styles/colunas.module.css'
// import {useState, useEffect} from "react"

export default function Dashboard(props) {
  // const [open, setOpen] = useState(false)

  // useEffect(() => {
  //   props.setViewCard(true)
  // })
  return (
    <>
      <Head>
        <title>OPPLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>


      <div className={colunas.bottomdiv}>
        <div className={colunas.colunaDiv}>
          <div className={colunas.containerColunas}>
            <Coluna1 
            // open={open}
            // setOpen={setOpen}
            {...props}
            setViewCard={(e) => props.setViewCard(e)}  />
          </div>
        </div>
        <div className={colunas.colunaDiv}>
          <div className={colunas.containerColunas}>
            <Coluna2 
            // open={open}
            // setOpen={setOpen}
            {...props} 
            setViewCard={(e) => props.setViewCard(e)}
            /></div>
        </div>
        <div className={colunas.colunaDiv}>
          <div className={colunas.containerColunas}>
            <Coluna3 
            // open={open}
            // setOpen={setOpen}
            {...props} 
            setViewCard={(e) => props.setViewCard(e)}/></div>
        </div>
        <div className={colunas.colunaDiv}>
          <div className={colunas.containerColunas}>
            <Coluna4 
            // open={open}
            // setOpen={setOpen}
            {...props} /></div>
        </div>
        <div className={colunas.colunaDiv}>
          <div className={colunas.containerColunas}>
            <Coluna5 
            // open={open}
            // setOpen={setOpen}
            {...props} 
            setViewCard={(e) => props.setViewCard(e)}/></div>
        </div>




      </div>

    </>


  )
}