// import Head from 'next/head'
// import QuickAdd from ".././components/cards/quickAdd"
// import { useState } from "react"
// // import styles from "../../styles/Home.module.css"


// export default  function Menu() {
//   const [addCard, setAddCard] = useState(false)

// //o menu terá que ter um state para aparecer e desaparecer

//   return (
//     <>

//     <Head>
//     <title>OPPLOG</title>
//     <meta name="description" content="Generated by create next app" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>

//     <div className='menuBar'>
//     <p>
//     <button 
//       onClick={() => setAddCard(true)}
//       className="botaoAdicionar">Add Card</button>
//       {addCard && <QuickAdd />}
//         </p>

//     </div>


//     </>
    

//   )
// }

