//LOGIN
import Head from 'next/head'
import { useState } from "react"
import { useRouter } from "next/router"
import styles from "../../../styles/signup.module.css"

export default function Login() {
  const router = useRouter()
  const routerLogin = useRouter()
  const [loginData, setloginData] = useState({
    EmailAddress: "aaa@aaa.aa",
    Password: "password"
  })
  const [statusAlert, setStatusAlert] = useState()

  const login = async () => {

    const res = await fetch(
      '../../api/login', {
      body: JSON.stringify(loginData),
      headers: {
        "Content-Type": "application/json",
      },
      method: "POST"
    })

    const json = await res.json()
    setStatusAlert(res.status)

    //se a resposta for positiva, faz login
    if (res.status === 200) {
      routerLogin.push("/plataforma")
      localStorage.setItem("tokenG3", json.token)
    }
    console.log(loginData, res.status, json)

  }

  return (
    <div className={styles.body}>
      <Head>
        <title>OPPLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <main className={styles.containerE1}>
        <aside className={styles.containerD1}>
          <img src="/picgroup.svg"></img>
          <img src="/logo.svg"></img>
        </aside>

        <form
          className={styles.containerForm}
          onSubmit={(e) => {
            e.preventDefault(),
              login()
          }}>


          <span className={styles.fontSignUp}></span>
          <label className={styles.fontSigninfo}> Email
            <input
              className={statusAlert === 404 ? `${styles.fontPassword} ${styles.input}` : styles.input}
              type="email"
              onChange={(e) => setloginData({ ...loginData, EmailAddress: e.target.value })}
              name="description"
              placeholder="Email"
              autoComplete="off"
              required />
          </label>

          <label className={styles.fontSigninfo}> Password
            <input
              className={statusAlert === 401 ? `${styles.fontPassword} ${styles.input}` : styles.input}
              type="password"
              name="description"
              onChange={(e) => setloginData({ ...loginData, Password: e.target.value })}
              placeholder="Insert Password"
              autoComplete="off"
              required /></label>

          <div style={{ padding: "20px" }}>
            <button
              className={styles.button1}
              value="Login"
            > Login
            </button>
            <button className={styles.button1} onClick={() => router.push('/')}>Return</button>
          </div>
        </form>


        <footer className={styles.footer}>©2022 Opplog. All rights reserved</footer>
      </main>
    </div>
  )
}