import Head from 'next/head'
import { useState } from "react"
import { useRouter } from "next/router"
import styles from "../../../styles/signup.module.css"




export default function Signup() {
  const router = useRouter()
  const routerLogin = useRouter()

  const [statusAlert, setStatusAlert] = useState()


  const [signupData, setSignupData] = useState({
    FirstName: 'name',
    LastName: 'name',
    EmailAddress: "aaa@aaa.aa",
    Password: 'password',
    passwordConfirmation: 'passwordConf',
    terms: false
  })

  const submit = async () => {
    const res = await fetch(
      '../../api/signUp', {
      body: JSON.stringify(signupData),
      headers: {
        "Content-Type": "application/json",
      },
      method: "POST"
    })
    const json = await res.json()

    setStatusAlert(res.status)


    if (res.status === 200) {
      routerLogin.push("/components/paginaInicial/login")
    } else {
      alert(`${json.message}.  ${json.errors.password ?? "Please verify your email."}`)
    }



    console.log(signupData, res.status, json)


  }

  return (
    <div className={styles.body}>

      <Head>
        <title>OPPLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main className={styles.containerE1}>
        <aside className={styles.containerD1}>
          <img src="/picgroup.svg"></img>
          <img className={styles.imgLogo}src="/logo.svg"></img>
        </aside>

        <form
          className={styles.containerForm}
          onSubmit={(e) => {
            e.preventDefault(),
              submit()
          }
          }>
          <span className={styles.fontSignUp}>Sign up</span>
          <label className={styles.fontSigninfo}> First Name
            <input
              className={styles.input}
              type="text"
              placeholder="Please Insert First Name here."
              onChange={(e) => setSignupData({ ...signupData, FirstName: e.target.value })}
              autoComplete="off"></input>
          </label>

          <label className={styles.fontSigninfo}> Last Name
            <input className={styles.input}
              type="text"
              placeholder="Please Insert Last Name here."
              onChange={(e) => setSignupData({ ...signupData, LastName: e.target.value })}
              autoComplete="off"></input>
          </label>

          <label className={styles.fontSigninfo}> Email
            <input className={styles.input}
              type="email"
              name="description"
              onChange={(e) => setSignupData({ ...signupData, EmailAddress: e.target.value })}
              placeholder="Email" autoComplete="off" />
          </label>
            
          <label className={styles.fontSigninfo}> Password
            <input className={statusAlert === 400 ? `${styles.fontPassword} ${styles.input}` : styles.input}
              type="password"
              name="description"
              placeholder="insert password here"
              onChange={(e) => setSignupData({ ...signupData, Password: e.target.value })}
              autoComplete="off" />
          </label>

          <label className={styles.fontSigninfo}> Repeat Password
            <input className={styles.input}
              type="password"
              name="description"
              onChange={(e) => setSignupData({ ...signupData, passwordConfirmation: e.target.value })}
              placeholder="Repeat password"
              autoComplete="off"></input>
          </label>

          <label className={styles.fontSigninfo}> Accept terms
            <input
              className={styles.inputCheck}
              type="checkbox"
              required
              onChange={(e) => setSignupData({ ...signupData, terms: !signupData.terms })}
              name=""></input>
          </label>
          <div style={{ padding: "20px" }}>
            <button className={styles.button1}
              value="Sign Up">
              Submit
            </button><button className={styles.button1} onClick={() => router.push('/')}>Return</button>
          </div>


        </form>

        <footer className={styles.footer}>©2022 Opplog. All rights reserved</footer>
      </main>
    </div>
  )
}